### ISSUE TITLE
Disk Cache not being used

### ISSUE THREAD

**Issue by Syer10** [qdsfdhvh/compose-imageloader#10]
I have a ImageLoader with DiskCache and MemoryCache configured but it seems to only be using the MemoryCache. My images use a custom class that I have Mappers and Keyers setup for but it doesnt seem to allow them to be inserted into the DiskCache even though they are loading the images. This happens on both Desktop and Android.

I have tried with multiple configurations using the builder and even disabling the memory cache, which does not seem to help. It doesnt seem like its hitting the DiskCacheInterceptor at all and Napier says nothing about errors.

In general I cannot figure out whats wrong.

**Comment by mipastgt** [comment]
Could you provide an example of how to configure the caches as this is not documented anywhere?

**Comment by mipastgt** [comment]
Thanks. I will have a look at it tomorrow. Its too late now :-)
