### ISSUE TITLE
Bad svg image quality

### ISSUE THREAD

**Issue by Bittner322** [qdsfdhvh/compose-imageloader#120]
Hello. I have a problem with your library.
This is result when i'm loading picture via your library:
<img width="398" alt="Снимок экрана 2023-04-14 в 01 10 17" src="https://user-images.githubusercontent.com/100136541/231859646-311c2f84-db36-456e-8d0c-352f0c116454.png">
This is the picture:
<img width="297" alt="Снимок экрана 2023-04-14 в 01 11 50" src="https://user-images.githubusercontent.com/100136541/231860053-85ad1377-67c2-4154-b9b6-00ca05c09834.png">
Actual fun:
`@Composable
actual fun rememberAsyncImagePainter(fileResource: FileResource): AsyncImagePainter {
    return rememberAsyncImagePainter(fileResource.rawResId)
}`
Expect fun:
`@Composable
expect fun rememberAsyncImagePainter(fileResource: FileResource): AsyncImagePainter`
Note: files storage is provided by [Moko-Resources](https://github.com/icerockdev/moko-resources)
Libraries versions:
imageloader:  1.2.10 (upgrading to 1.3.1 did no impact)
compose: 1.3.0-rc05
moko-resources: 0.20.1

**Comment by qdsfdhvh** [comment]
Try to see if a configuration like the one below can be fixed?
```kotlin
ImageLoader {
    ...
    components {
        setupDefaultComponents(
            useSvgSizeFirst = true
        )
    }
    ...
}
```

**Comment by qdsfdhvh** [comment]
Hi, I switched out of the old solution and handled it the same way as [SVGPainter](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/res/DesktopSvgResources.desktop.kt#L59), this way the default size of the svg may be more accurate.
