### ISSUE TITLE
image-loader gradle commonMain dependency overwrites androidx.compose.ui.window.Popup

### ISSUE THREAD

**Issue by morgan4080** [qdsfdhvh/compose-imageloader#147]
After adding image-loader api dependency to commonMain in shared build.gradle.kts, androidx.compose.ui.window.Popup imports cannot be found in commonMain kotlin files with error (Unresolved reference: Popup)

**Comment by qdsfdhvh** [comment]
Hi, Thanks for using it. could it be caused by a different version of `compos-multiplatofrm? `imageloader 1.4.1` uses `compose-multiplatform 1.4.0`.

**Comment by qdsfdhvh** [comment]
I'm close this issue, you can reopen it if still have problem.
