### ISSUE TITLE
Support for WASM

### ISSUE THREAD

**Issue by DRSchlaubi** [qdsfdhvh/compose-imageloader#151]
I tried using this with compose `1.4.0-dev-wasm06` and it conflicts with that version, so I cannot use it

**Comment by qdsfdhvh** [comment]
This may take some time, some of the current dependencies such as `kotlinx.coroutines` have not add wasm target yet.

**Comment by DRSchlaubi** [comment]
https://github.com/Kotlin/kotlinx.coroutines/issues/3713
https://youtrack.jetbrains.com/issue/KTOR-5587/Ktor-client-for-Kotlin-Wasm

**Comment by qdsfdhvh** [comment]
@DRSchlaubi  I've just released a version 1.6.4-wasm0, you can try it out.

**Comment by nowiwr01w** [comment]
@qdsfdhvh hi, how to use wasm version? and what's the latest version?`Could not find io.github.qdsfdhvh:image-loader:1.6.4-wasm0.`
```
repositories {
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    maven("https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental")
    maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev")
    google()
    gradlePluginPortal()
    mavenCentral()
}
```

**Comment by qdsfdhvh** [comment]
I uploaded `mavenCentral ` before, but the version seems to be missing, I will going to reorganise an wasm version.

**Comment by qdsfdhvh** [comment]
@nowiwr01w I've just published `1.7.2-SNAPSHOT` version, you can test it.

```
 repositories {
    maven("https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental") // for ktor 3.0.0-wasm2
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
}

dependencies {
    implementation("io.github.qdsfdhvh:image-loader:1.7.2-SNAPSHOT")
}

```

**Comment by AYastrebov** [comment]
Any plans to add wasm target support to release?

**Comment by qdsfdhvh** [comment]
Now, I am waiting for ktor to release a full version 3.0.0 with wasm.
