### ISSUE TITLE
Web app console error: Its dependency '@js-joda/core' was not found

### ISSUE THREAD

**Issue by sunildhiman90** [qdsfdhvh/compose-imageloader#154]
Hi after adding compose-imageloader dependency in my compose multiplatform project, i m getting following error in web app console and app is not loading anything:

`caught Error: Error loading module 'compose-instagram-clone-multiplatform'. Its dependency '@js-joda/core' was not found. Please, check whether '@js-joda/core' is loaded prior to 'compose-instagram-clone-multiplatform'.`

where compose-instagram-clone-multiplatform is my project name just for clarifications.

If i remove this dependency , it works fine. any idea about this issue?

**Comment by qdsfdhvh** [comment]
It seems to be caused by `okio-fakefilesystem` referencing [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime/blob/master/core/build.gradle.kts#LL200C21-L200C21), I'll remove the js default `filesystem` later.

**Comment by sunildhiman90** [comment]
Hi @qdsfdhvh, thanks. By when it will be fixed? and till then can we have any workaround for making this working for web?
Thanx

**Comment by qdsfdhvh** [comment]
I'm posting `1.4.3`, reopen this issue if you still have problems.

**Comment by sunildhiman90** [comment]
Sure, i will check it and update you.

**Comment by sunildhiman90** [comment]
Hi @qdsfdhvh , how much time it takes for the release to available, currently i am getting following error:

```
  > Could not find io.github.qdsfdhvh:image-loader:1.4.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/github/qdsfdhvh/image-loader/1.4.3/image-loader-1.4.3.pom
       - https://repo.maven.apache.org/maven2/io/github/qdsfdhvh/image-loader/1.4.3/image-loader-1.4.3.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/io/github/qdsfdhvh/image-loader/1.4.3/image-loader-1.4.3.pom
```

**Comment by sunildhiman90** [comment]
@qdsfdhvh, Its working fine now, thanks for great support.
