### ISSUE TITLE
Placeholder while loading the image

### ISSUE THREAD

**Issue by iadcialim** [qdsfdhvh/compose-imageloader#164]
How to put a placeholder image?
Or at least for now able to know if loading of image is successful or not.

**Comment by qdsfdhvh** [comment]
You can use `ImageRequestState`, some like [this](https://github.com/qdsfdhvh/compose-imageloader/blob/master/app/common/src/commonMain/kotlin/com/seiko/imageloader/demo/scene/Common.kt#LL90C6-L90C6).
```kotlin
val painter = rememberAsyncImagePainter(request)
// Image() 
when (painter.requestState) {
    is ImageRequestState.Loading -> {
        // here
    }
    is ImageRequestState.Failure -> Unit
    ImageRequestState.Success -> {
        // Image()
    }
}
```

**Comment by iadcialim** [comment]
Thanks @qdsfdhvh
