### ISSUE TITLE
Memory/Disk cache support on all platforms

### ISSUE THREAD

**Issue by iadcialim** [qdsfdhvh/compose-imageloader#165]
I am trying to implement this section [Memory/Disk cache support on all platforms](https://github.com/qdsfdhvh/compose-imageloader#memorydisk-cache-support-on-all-platforms).

Aside from README file, I can't find usage in the sample code.

Questions:
1. Which location or file to put the all the actual implementation here?
```
//actuals on the platforms:
//Android
actual fun ComponentRegistryBuilder.setupDefaultComponents() = this.setupDefaultComponents(App.context)
actual fun getImageCacheDirectoryPath(): Path = App.context.cacheDir.absolutePath.toPath()

//iOS
actual fun ComponentRegistryBuilder.setupDefaultComponents() = this.setupDefaultComponents()
actual fun getImageCacheDirectoryPath(): Path {
    val cacheDir = NSSearchPathForDirectoriesInDomains(
        NSCachesDirectory,
        NSUserDomainMask,
        true
    ).first() as String
    return (cacheDir + "/media").toPath()
}

//Desktop
actual fun ComponentRegistryBuilder.setupDefaultComponents() = this.setupDefaultComponents()
actual fun getImageCacheDirectoryPath(): Path = "media/".toPath()
```

2. What is `App` in `App.context.` ?

I am very new to Kotlin Multiplatform, so can't get it at first if this is quite obvious to you.

**Comment by qdsfdhvh** [comment]
This part of the documentation is provided by the community, so it will be different from the `sample`, sorry I haven't had time to improve the documentation.

about qustion 2 use:
```kotlin
class DemoApp : Application() {
    override fun onCreate() {
        super.onCreate()
        context = this
    }
    companion object {
        lateinit var context : Application
    }
}
```
and use `DemoApp.context`.

Personally, I still prefer to provides  `LocalImageLoader` on each platform, like [sample](https://github.com/qdsfdhvh/compose-imageloader/blob/master/app/android/src/main/java/com/seiko/imageloader/demo/MainActivity.kt#LL21C42-L21C42).

**Comment by iadcialim** [comment]
@qdsfdhvh 

> Personally, I still prefer to provides LocalImageLoader on each platform, like [sample](https://github.com/qdsfdhvh/compose-imageloader/blob/master/app/android/src/main/java/com/seiko/imageloader/demo/MainActivity.kt#LL21C42-L21C42).

 Do you have a sample code for iOS?

**Comment by iadcialim** [comment]
Never mind. Got it here https://github.com/qdsfdhvh/compose-imageloader/blob/master/app/ios-combine/src/commonMain/kotlin/com/seiko/imageloader/demo/Main.kt
