### ISSUE TITLE
Improve support for locally provided image data

### ISSUE THREAD

**Issue by chris-hatton** [qdsfdhvh/compose-imageloader#18]
Thank you for producing and sharing this library; the power of the Compose/Multiplatform ecosystem is beginning to show!

While the cross-platform ability is great; I noticed you have focused API's on loading resources asynchronously.
My use case is for showing SVG (and potentially other format) files from local bytes which are much faster to load and so the overhead of managing a progress 'spinner' etc. is undesirable.

If you are planning any major new features for this library; please consider building API's intended for local resources: that take byte data for images directly, and minimise overhead to display.

**Comment by qdsfdhvh** [comment]
It can be used like this:
```kotlin
Image(
    painter = rememberAsyncImagePainter(url),
    contentDescription = null,
)
```
0ur internal project was really slow in loading some web3 images, so added `requestState`, but it is not required.
