### ISSUE TITLE
Small size of svg images

### ISSUE THREAD

**Issue by klusi** [qdsfdhvh/compose-imageloader#180]
After update to 1.5.1 (from 1.3.1), there is broken size of some downloaded SVG images. I would like the image to fill the entire image view. Here's en example of two similar SVG images and comparison with Coil-Compose:
![imageloader](https://github.com/qdsfdhvh/compose-imageloader/assets/30256647/722d1557-8812-45e9-8b64-87f95192775a)
As you can see, one of the images has broken size and setting contentScale or other imageLoader options has no effect to it.
Here's my code:
```
    Image(
        painter = rememberAsyncImagePainter(
            url = url,
            contentScale = ContentScale.FillWidth,
        ),
        contentDescription = null,
        modifier = Modifier
            .size(50.dp)
            .background(color = Color.Red),
        contentScale = ContentScale.FillWidth,
    )
```
I have attached a demo project - [ImageDemo.zip](https://github.com/qdsfdhvh/compose-imageloader/files/11748016/ImageDemo.zip)

Versions:
ImageLoader - 1.5.1
Kotlin - 1.8.20
Compose - 1.4.0
Gradle - 8.0.2

**Comment by klusi** [comment]
@qdsfdhvh Thanks for fix. When you upload new release (1.5.2) to maven please?

**Comment by qdsfdhvh** [comment]
Sorry, the configuration was changed incorrectly and the uploaded version code is missing, I am re-uploading it now.
