### ISSUE TITLE
Targeting JDK 17 breaks Android

### ISSUE THREAD

**Issue by chrisbanes** [qdsfdhvh/compose-imageloader#197]
Seems that 1.5.2 includes a25bfd7b5f945abe9c2613734fd47c9b9c205284 which now targets JDK 17. Why?

This breaks Android builds (which only really support up to JDK 11).

**Comment by qdsfdhvh** [comment]
I thought many kmp projects were already using jdk 17, that's why I tried to upgrade, I'll release 1.5.3 later to downgrade to jvmTarget 11.
