### ISSUE TITLE
Expected class ImageLoaderBuilder does not have default constructor

### ISSUE THREAD

**Issue by mipastgt** [qdsfdhvh/compose-imageloader#21]
For this part of your example usage code
```
private fun generateImageLoader(): ImageLoader {
    return ImageLoaderBuilder().build()
}
```
 IntelliJ is giving me the error message
```
Expected class ImageLoaderBuilder does not have default constructor
```
This must be an IntelliJ issue because the code compiles and runs just well but maybe this error message could be avoided if you would just provide that default constructor in your code.

Otherwise your code seems to work nicely. Great job!

**Comment by qdsfdhvh** [comment]
Sure, I'll try it.

**Comment by qdsfdhvh** [comment]
I've tried it and I can't define a default constructor for the ImageLoader, in android I have to pass in the `context`.

**Comment by mipastgt** [comment]
No problem. It's just an IntelliJ issue anyway.
