### ISSUE TITLE
Cache blocks re-loading of images after failed attempts

### ISSUE THREAD

**Issue by mipastgt** [qdsfdhvh/compose-imageloader#23]
If the image loader cannot successfully download an image on the first try, then, when caching is enabled, it does not make any attempt to download the image again at a later time. When the disk cache is enabled it does not even retry this when the application is terminated and started again. It seems that even in case of a download error something is stored in the cache which then blocks any further attempts. I tested this by removing my images from my server, then start the application, then copy the images back to the server while the application is still running. Switching screens or restarting the application does not force a re-load of the images. This all works when no caching is configured but this is no option for me.

I have configured caching like this:

```
    fun generateImageLoader(): ImageLoader {
        return ImageLoaderBuilder().apply {
            diskCache {
                DiskCacheBuilder()
                    .directory("... path to some cache directory ...".toPath())
                    .maxSizeBytes(1024 * 1024 * 50) // 50 MB
                    .build()
            }
            memoryCache {
                MemoryCacheBuilder()
                    .build()
            }
        }.build()
    }

```

**Comment by qdsfdhvh** [comment]
Does the service return 200 when downloading the wrong thing?
The current caching policy is indeed rather rigid and I will be improving it in the near future.

**Comment by mipastgt** [comment]
I don't know what the server response was in these cases, especially as there are various different scenarios where this seems to happen.

**Comment by qdsfdhvh** [comment]
I try added the http status code check and custom cache policy to the image request, It might help a little.
