### ISSUE TITLE
rememberImageAction does not change image by new url

### ISSUE THREAD

**Issue by jershell** [qdsfdhvh/compose-imageloader#235]
version 1.6.2
kotlin 1.8.2
platform ios
compose 1.4.3

i have a code

```kotlin
@Composabe
fun myAsyncImage(url: String) {
        val imageAction by rememberImageAction(url)
        val painter = rememberImageActionPainter(imageAction)
}
```
and then i changed a url happend nothing.

workaround

```kotlin
@Composable
private fun fixedRememberImageAction(
    url: String,
    imageLoader: ImageLoader = LocalImageLoader.current,
): State<ImageAction> {
    val request = >>>>remember(url)<<<< { ImageRequest(url) }
    return rememberImageAction(request, imageLoader)
}

```
Please, can you fix the `rememberImageAction`?

**Comment by qdsfdhvh** [comment]
Thanks for the feedback, I'll be releasing a new version today to fix it!

**Comment by QiXi** [comment]
I see this bug repeating on version 1.6.3
When you change the url, the image sometimes changes, but more often it does not.

**Comment by qdsfdhvh** [comment]
> I see this bug repeating on version 1.6.3
> When you change the url, the image sometimes changes, but more often it does not.

I'll check again today.

**Comment by qdsfdhvh** [comment]
I find the reason, here sometimes is not `image -> load -> image`, and is `image -> image`, so `remember` not recompose, i, I has fixed it.

https://github.com/qdsfdhvh/compose-imageloader/blob/a63c3c0b684b7e4565c5f4f924942fc8a1bb668d/image-loader/src/commonMain/kotlin/com/seiko/imageloader/Remember.kt#L54
https://github.com/qdsfdhvh/compose-imageloader/blob/a63c3c0b684b7e4565c5f4f924942fc8a1bb668d/image-loader/src/commonMain/kotlin/com/seiko/imageloader/Remember.kt#L57
https://github.com/qdsfdhvh/compose-imageloader/blob/a63c3c0b684b7e4565c5f4f924942fc8a1bb668d/image-loader/src/commonMain/kotlin/com/seiko/imageloader/Remember.kt#L60

**Comment by QiXi** [comment]
cool, it's working now
