### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ScottPierce** [qdsfdhvh/compose-imageloader#24]
Please provide a changelog, or some other means, so we know what version of Compose each version matches with and which version of ktor it uses as well.

**Comment by qdsfdhvh** [comment]
I'll bring CHAGELOG for later updates, like this:

---
# What's Changed

  - xxx #00
  - xxx #00

### Full Changelog: [1.2.0...1.2.1](https://github.com/qdsfdhvh/compose-imageloader/1.2.0...1.2.1)
---

I haven't maintained an CHAGELOG before, it might be rough at first.

**Comment by ScottPierce** [comment]
That would be super helpful, especially with how exact the versions of Kotlin, Compose, etc have to be right now.
