### ISSUE TITLE
ImageLoader httpClient

### ISSUE THREAD

**Issue by mahramane** [qdsfdhvh/compose-imageloader#266]
Hi

```
val painter = rememberImagePainter(
                    url = "https://example.com/image",
                    imageLoader = generateImageLoader()
                )
                Image(
                    modifier = Modifier.size(70.dp, 70.dp).clip(CircleShape),
                    painter = painter,
                    contentDescription = null
                )
```

```
@Composable
fun generateImageLoader(
    tokenManager: TokenManager = koinInject()
): ImageLoader {
    return ImageLoader {
        components {
            setupDefaultComponents(
                httpClient = {
                    HttpClient{
                        defaultRequest {
                            bearerAuth(tokenManager.getAuthorization)
                        }
                    }
                }
            )
        }
    }
}
```

Hi
when i set image loader for rememberImagePainter, i got the following error:

io.ktor.client.HttpClient -- REQUEST https://example.com/image failed with exception: java.util.concurrent.CancellationException: The coroutine scope left the composition

how can i fix that?

**Comment by qdsfdhvh** [comment]
You need to `remember { generateImageLoader() } ` otherwise it will cause the `Imageloader` to rebuild on `Recompose`.

<img src="https://github.com/qdsfdhvh/compose-imageloader/assets/17807925/00b243b6-f0b8-4f1c-95ca-423889723f47" width="400" />

But the bettter way is use `CompositionLocalProvider` at the outer level of the compose.

```kotlin
setContent {
    CompositionLocalProvider(
        LocalImageLoader provides remember { generateImageLoader() }
    ) {
        // App()
    }
}
```

**Comment by qdsfdhvh** [comment]
I'm close this issue, you can reopen it if still have problem.
