### ISSUE TITLE
Possible disk space leak

### ISSUE THREAD

**Issue by QiXi** [qdsfdhvh/compose-imageloader#271]
After I built in the function to calculate the size of the application's cache, I found the following behavior:
every time I open a screen with multiple images (including GIFs), the application cache size increases by 6MB (images are always the same)

This behavior only happens on a real device with `Android 9.0`
The files have the format name `tmp[NUMBER].tmp`
The files are created at `/data/user/0/[App]/cache/` and may not have a space limit.

Through searching for `tmp` I found this line:

https://github.com/qdsfdhvh/compose-imageloader/blob/2ebdc1e5478e8888836c16291b4b50c0b370a8ad/image-loader/src/androidMain/kotlin/com/seiko/imageloader/component/decoder/ImageDecoderDecoder.kt#L97

The original files are also located along the path `/data/user/0/[App]/cache/image_cache`

**Comment by qdsfdhvh** [comment]
This code was copied from `coil`, I had to research what it does first and then fix it.

**Comment by QiXi** [comment]
After studying, did you understand the essence of the problem? Or do I need to provide additional information?
after a minute of using the application, the cache size can increase to 500 MB, which is a critical problem. If needed, I can provide Gif images or help run tests.

**Comment by qdsfdhvh** [comment]
I've fixed it, but still testing.

**Comment by qdsfdhvh** [comment]
@QiXi Hi, can you help me try this branch  #273 is fixes this problem?

**Comment by QiXi** [comment]
> @QiXi Hi, can you help me try this branch #273 is fixes this problem?

Unfortunately, I experienced a number of difficulties when connecting the dependency through the source code.

After connecting `1.6.5`, the problem is gone and the cache does not increase when viewing the same pictures.

I also wanted to check the validity of the need to use write to disk file every time on the Android API 28

```
val temp = File.createTempFile("tmp", null)
FileSystem.SYSTEM.write(temp.toOkioPath()) {
	writeAll(source)
}
ImageDecoder.createSource(temp)
```
