### ISSUE TITLE
Min SDK Version changed

### ISSUE THREAD

**Issue by takahirom** [qdsfdhvh/compose-imageloader#288]
Hello, I've noticed that the minimum SDK version has changed in the latest release, but there was no mention of this in the release notes. Is this change intentional?

Affected Version: 1.6.5
Expected Behavior: Min SDK Version should be consistent with previous versions or mentioned in release notes if changed.
Actual Behavior: Min SDK Version changed without any notice.
Thank you for your time and effort on this project.

https://github.com/qdsfdhvh/compose-imageloader/compare/1.6.4...1.6.5

**Comment by qdsfdhvh** [comment]
Sorry, it's my mistake, I'll change it back to minSdk=21 right now.
