### ISSUE TITLE
Why use Batik based SVG renderer on desktop

### ISSUE THREAD

**Issue by mipastgt** [qdsfdhvh/compose-imageloader#29]
For the desktop version you are using the Batik based twelvemonkeys SVG renderer. Why do you do that? All desktop versions are also Skia versions and thus have the Skia SVG built in. It would save people from a lot of dependency downloads if you would drop that. The Skia SVG renderer works nicely on desktop so I don't see any reason to use the Batik one. It would make the final distribution bundles smaller.

**Comment by qdsfdhvh** [comment]
skia's svg are not well support, like:[metamask-fox](https://raw.githubusercontent.com/MetaMask/brand-resources/master/SVG/metamask-fox.svg).
 I am now trying to implement this piece of parsing myself, but it will take some time, I'll bring up batik later.
