### ISSUE TITLE
1.7.0 version doesn't load image on android

### ISSUE THREAD

**Issue by ashiqulbkash** [qdsfdhvh/compose-imageloader#359]
```
                   Image(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(200.dp),
                        painter = rememberImagePainter(product.image),
                        contentDescription = null
                    )
```

If I change the version to 1.2.8. & 1.6.0 & 1.6.8

Then the image loads successfully on android

**Comment by qdsfdhvh** [comment]
Maybe the ktor engine is missing, which is my negligence. I forgot to explain in the document that I removed the default ktor engine. I will update the document later. #333

**Comment by joreilly** [comment]
Hi, seeing same issue.....wasn't clear from above what the solution is?

**Comment by qdsfdhvh** [comment]
It's a bit of a pain to manually add the ktor engine to each target, I'm going to post a new version to withdraw this change!

**Comment by qdsfdhvh** [comment]
You can test 1.7.1 and reopen it if there are still problems.
