### ISSUE TITLE
Error on JS Web

### ISSUE THREAD

**Issue by SEAbdulbasit** [qdsfdhvh/compose-imageloader#403]
I am trying to load the image on Compose Web, but I am getting the following error:

![Screenshot 2023-12-16 at 3 39 08 PM](https://github.com/qdsfdhvh/compose-imageloader/assets/33172684/5907e3fa-c8eb-4ab7-b958-b08f9620e805)

I'm not sure if it is a JS issue or some issue on the library end. I have used this library before a Web project and it worked fine.

You can find the source code here: https://github.com/SEAbdulbasit/ImageAppKMP

**Comment by qdsfdhvh** [comment]
Hi, I tested it and it seems to be a problem with the `compose-multi platform` version, I changed it to `1.5.11` and it works fine!

https://github.com/qdsfdhvh/ImageAppKMP/commit/9709b083cef96d18689b3dad2e073a991d375c13

**Comment by SEAbdulbasit** [comment]
Working fine, thank you so much 🙇
