### ISSUE TITLE
AutoSizeBox not re-rendering when url changes

### ISSUE THREAD

**Issue by joreilly** [qdsfdhvh/compose-imageloader#469]
Hi, I'm using version `1.7.6` and `AutoSizeBox` and it's not rendering new image when the url changes. I only seem to be seeing this though in the Compose for Desktop client.  It should be possible to see this happening by running that client in https://github.com/joreilly/Confetti.  The following is how it's used so maybe something I'm not doing correctly here (in `SessionDetailsViewShared.kt`)

```
                AutoSizeBox(speaker.photoUrl) { action ->
                    when (action) {
                        is ImageAction.Success -> {
                            Image(
                                rememberImageSuccessPainter(action), null,
                                modifier = Modifier.size(64.dp).clip(CircleShape),
                                contentScale = ContentScale.Crop,
                            )
                        }
                        is ImageAction.Loading -> {
                            CircularProgressIndicator()
                        }
                        is ImageAction.Failure -> {
                            Image(
                                painter = painterResource(Res.drawable.ic_person_black_24dp),
                                contentDescription = speaker.name,
                                contentScale = ContentScale.Fit,
                                modifier = Modifier.size(64.dp).clip(CircleShape)
                            )
                        }
                    }
                }
```

**Comment by qdsfdhvh** [comment]
It’s seem similar to my previous [fix](https://github.com/qdsfdhvh/compose-imageloader/pull/444/files) of `AutoSizeImage, on desktop `invalidateMeasurement` will not trigger `invalidateDraw`.
Can you help me to try `AutoSizeImage` can run fine? `AutoSizeBox` could also be for a more similar reason, but needs further investigation.

**Comment by joreilly** [comment]
Yes, `AutoSizeImage` works fine.
