### ISSUE TITLE
js image loading not working in 1.2.8

### ISSUE THREAD

**Issue by jeran** [qdsfdhvh/compose-imageloader#54]
hey, thanks for the work on this.

we're trying to adopt this library for js, but version 1.2.8 doesn't seem to be working for us (nothing loads). our code is fairly straightforward:

```kotlin
onWasmReady {
    Window("") {
        CompositionLocalProvider(
            LocalImageLoader provides ImageLoader {
                logger = DebugLogger(LogPriority.VERBOSE)
                components {
                    setupDefaultComponents(imageScope)
                }
                interceptor {
                    memoryCacheConfig {
                        maxSizePercent(0.25)
                    }
                }
            },
        ) {
            Image(
                modifier = Modifier.fillMaxSize(),
                painter = rememberAsyncImagePainter("https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"),
                contentDescription = "",
                contentScale = ContentScale.Crop,
            )
        }
    }
}
```
this roughly matches the image loader configuration in the js sample [here](https://github.com/qdsfdhvh/compose-imageloader/blob/master/app/web/src/jsMain/kotlin/Main.kt). i've also tried with just `ImageLoader { }` and also without providing our own. but unfortunately, all approaches have resulted in nothing loading.

here are the logs we're seeing:
```
DEBUG MappedInterceptor : [image data] https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
[message] map -> https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
build.umd.js:3103 WARNING AsyncImagePainter : [image data] https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
[message] load image error
```

the last version I tried was 1.2.5 and that worked without a problem, but we're looking to update to jb-compose:1.3.0.

any thoughts?

**Comment by qdsfdhvh** [comment]
Okay, I'll fix it.

**Comment by qdsfdhvh** [comment]
1.2.9 is publishing, try to see if this issue is fixed.

**Comment by jeran** [comment]
awesome. will check it first thing in the morning

**Comment by jeran** [comment]
thank you for the quick response! unfortunately I still haven't gotten it working. there is a new set of logs though:

```
DEBUG MappedInterceptor : [image data] https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
[message] map -> https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
build.umd.js:3103 TRACE: Adding Accept-Charset=UTF-8 to https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
build.umd.js:3103 TRACE: Validating response for request https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
build.umd.js:3103 TRACE: Skipping default response validation for https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
build.umd.js:3103 TRACE: Transformed with default transformers response body for https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png to class ByteReadChannel
build.umd.js:3103 WARNING AsyncImagePainter : [image data] https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
[message] load image error
```

**Comment by qdsfdhvh** [comment]
Okay, I will look it on Monday.

**Comment by qdsfdhvh** [comment]
Hi, I tested it's works in the demo by removing the `customKtorUrlFetcher`(some custom headers),  maybe it's a similar reason for this.

code: https://github.com/qdsfdhvh/compose-imageloader/pull/57

<img width="300" alt="image" src="https://user-images.githubusercontent.com/17807925/218362345-fa1f6927-9d26-4e54-9f70-02bead0cacf6.png">

**Comment by jeran** [comment]
got it. will take a look tomorrow!

**Comment by jeran** [comment]
i updated the logger to print the exception and got:

```
AsyncImagePainter : NoTransformationFoundException: No transformation found: class ByteChannelJS -> class ByteReadChannel
with response from https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png:
status: 200 
response headers: 
cache-control: max-age=300
, content-length: 543
, content-type: image/png
, expires: Mon, 13 Feb 2023 21:36:09 GMT
```

looks like its thrown somewhere in `io.ktor.client.call.HttpClientCall`

unfortunately I need to cycle off of this for now, but I'll see if I can get back to it in the future

**Comment by qdsfdhvh** [comment]
Good luck, and can you provide a demo?

**Comment by jeran** [comment]
yeah, right now i'm testing it pretty deep in our project (we embed a jb-compose window inside of a larger web app), but once i get the chance i'll see if i can isolate it. thanks for the quick responses!

**Comment by jeran** [comment]
hey, made some time this weekend. I have a repro here https://github.com/jeran/image-loader-bug see the latest commit.

I have this feeling I'm just missing something entirely obvious in the setup, but hope this helps us narrow down the issue.

thanks again for your time

**Comment by qdsfdhvh** [comment]
Hi, I upgraded [kotlin to 1.8.0](https://github.com/qdsfdhvh/image-loader-bug/commit/d7165a5758ebfdd16f0ef9b1bf710d765495cde3) and it can be displayed normally, I'm not quite sure why, you can try to see if this can be solved.
