### ISSUE TITLE
Displaying the same SVG at different sizes on the same screen cause rendering issues

### ISSUE THREAD

**Issue by coderforlife** [qdsfdhvh/compose-imageloader#608]
If the same SVG is displayed at two different sizes on the same screen, then it is rendered very oddly (both sizes are rendered on top of each other in both locations).

**Comment by qdsfdhvh** [comment]
The reuse of painter is a bit of a problem, the current workaround is that you can hide this painter cache, I'll try to fix it later on.
```kotlin
ImageLoader {
  interceptor {
    // painterMemoryCacheConfig {
    //     maxSize(50)
    // }
  }
}
```
