### ISSUE TITLE
Making breaking changes in minor version?

### ISSUE THREAD

**Issue by ScottPierce** [qdsfdhvh/compose-imageloader#79]
I just updated from 1.2.0 to 1.2.9. It's a little odd to see breaking API changes in a bug version change. Are you following semantic versioning?

**Comment by qdsfdhvh** [comment]
Sorry, I didn't know about `semantic versioning` before, I will provide support for the old api in the next version.

**Comment by ScottPierce** [comment]
You don't need to do that. If you follow semantic versioning in the future,
that will be helpful to most people. Most breaking API changes require a
minor version change.

**Comment by qdsfdhvh** [comment]
Okay, I'll adjust the format of the version and it will follow `semantic versioning` in the future.
